# Generated by Django 2.0.2 on 2018-02-27 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1024)),
                ('slug', models.CharField(max_length=1024, unique=True)),
                ('summary', models.TextField(default='')),
                ('body', models.TextField()),
                ('post_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
