# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('slug', models.CharField(max_length=1024, unique=True)),
                ('body', models.TextField()),
                ('post_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
