# Generated by Django 2.1.2 on 2018-10-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image_alt_text',
            field=models.CharField(blank=True, max_length=1025, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image_url',
            field=models.CharField(blank=True, max_length=1025, null=True),
        ),
    ]
