# Generated by Django 2.1 on 2018-09-26 22:26

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
        migrations.AddField(
            model_name='person',
            name='hashed_password',
            field=models.BinaryField(default=b'abc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='api_key',
            field=models.CharField(blank=True, default=people.models.generate_api_key, max_length=255, unique=True),
        ),
    ]
