# Generated by Django 2.1 on 2018-09-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180926_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hashed_password',
            field=models.CharField(max_length=255),
        ),
    ]
