# Generated by Django 2.1 on 2018-09-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180926_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hashed_password',
            field=models.BinaryField(max_length=255),
        ),
    ]
