# Generated by Django 2.1 on 2018-08-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20180807_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
