# Generated by Django 2.1 on 2018-09-07 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20180811_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sort_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 19, 1, 46, 772503)),
            preserve_default=False,
        ),
    ]
