# Generated by Django 2.1 on 2018-09-16 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20180909_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
    ]
