# Generated by Django 2.1 on 2018-09-23 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20180923_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_project', to='portfolio.Project'),
        ),
    ]
