# Generated by Django 2.0.2 on 2018-03-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.TextField(default='')),
                ('uuid', models.TextField(default='')),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
    ]
