# Generated by Django 2.1 on 2018-09-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
