# Generated by Django 2.1 on 2018-09-16 13:44

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_upload_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='filename',
        ),
        migrations.AlterField(
            model_name='upload',
            name='upload',
            field=models.FileField(upload_to=uploads.models.upload_file),
        ),
    ]
