# Generated by Django 2.1 on 2018-09-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_auto_20180923_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='uuid',
            field=models.UUIDField(blank=True, unique=True),
        ),
    ]
