# Generated by Django 2.1 on 2018-09-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_auto_20180923_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='uuid',
            field=models.CharField(blank=True, max_length=1024, unique=True),
        ),
    ]
